### ISSUE TITLE
控制台报错

### ISSUE THREAD

**Issue by histion** [chanshiyucx/aurora#48]
![QQ截图20220810101444](https://user-images.githubusercontent.com/65994410/183795547-ed2f5d1c-eb25-4434-9cff-40efd806323c.png)
表现为无法加载首页内容，挂梯子可正常加载

**Comment by Septillions** [comment]
leancloud 绑定自己的域名可解决，[leancloud 公告](https://forum.leancloud.cn/t/2022-8/25408)
