### ISSUE TITLE
希望能添加rss功能

### ISSUE THREAD

**Issue by Auier** [chanshiyucx/aurora#9]
RT

**Comment by muzi502** [comment]
由于使用的 GitHub 的 issue 进行内容管理，可以使用 [rsshub](https://rsshub.app/) 来订阅 GitHub repo 上的 issue 。

格式：```https://rsshub.app/github/issue/${user}/${repo}```

比如：```https://rsshub.app/github/issue/chanshiyucx/blog```

![image](https://user-images.githubusercontent.com/42566386/74123366-82237580-4c09-11ea-8a25-628b975fe8cb.png)
但打开后的是 issue 的地址，所以还需要到原站（
